ecommerce_poc/ecommerce/urls.py
from django.urls import path, include
from . import views
from .views import (
  CreateCheckoutSessionView,
  CancelView
)
from django.contrib.auth.views import LoginView

app_name = 'ecommerce'

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    # path('auth0/', include('social_django.urls', namespace='social')),
    path('leave_question/<int:id>/<str:category>/', views.leave_question, name='leave_question'),
    path('leave_review/<int:id>/<str:category>/', views.leave_review, name='leave_review'),
    path('send_receipt/', views.send_receipt, name='send_receipt'),
    path('collect_delivery_info/', views.collect_delivery_info, name='collect_delivery_info'),
    path('contact_us_page_success/', views.contact_us_page_success, name='send_customer_question'),
    path('send_customer_question/', views.send_customer_question, name='send_customer_question'),
    path('contact_us/', views.contact_us_page, name='contact_us_page'),
    path('about/', views.about_page, name='about_page'),
    # authlib related oauth paths
    path("", views.index, name="index"),
    path("auth0_login", views.auth0_login, name="auth0_login"),
    path("auth0_logout", views.auth0_logout, name="auth0_logout"),
    path("callback", views.callback, name="callback"),
    # auth0 related url paths, next 3 lines
    path('profile/', views.profile, name='profile'),
    #path('login/', views.login, name='login'),
    #path('logout/', views.logout, name='logout'),
    path('item/<int:id>/<str:category>/', views.item_page, name='item_page'),
    path('cart/', views.cart_page, name='cart_page'),
    path('remove_item_from_cart/<int:id>/', views.remove_item_from_cart, name='remove_item_from_cart'),
    path('add_item_to_cart/<int:id>/', views.add_item_to_cart, name='add_item_to_cart'),
    path('register_new_user/', views.register_new_user, name='register_new_user'),
    path('register_done/', views.register_done, name='register_done'),
    path('user_checkout/', views.user_checkout, name='user_checkout'),
    path('create-checkout-session/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('payment_success/', views.successful_payment, name='payment_success'),
    path('payment_cancel/', CancelView.as_view(), name='payment_cancel'),
    path('filter_results_page/<str:category>/', views.filter_results_page, name='filter_results_page'),
]

ecommerce_poc/ecommerce_poc/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('ecommerce.urls', namespace='ecommerce')),
    path('ecomm/', include('ecommerce.urls', namespace='ecommerce')),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

ecommerce_poc/ecommerce/views.py
from django.shortcuts import render, redirect
from ecommerce.models import Delivery, ProductQuestion, ProductAnswer, ProductReview, Customer, KitchenAndHomeAppliance, KitchenAndHomeApplianceFilter, SportsNutrition, SportsNutritionFilter, BaseProduct, Generator, GeneratorFilter, Price, GameConsole, GameConsoleFilter, HomeDecor, HomeDecorFilter, CartItem
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views import View
from django.http import HttpResponse
from django.conf import settings
from django.views.generic import TemplateView
from django.db.models import F
# this is temporary to get our ajax function working to do some testing, do not do this in production!
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from django.core.exceptions import ObjectDoesNotExist
import json
# auth0 related imports, next 3 lines
from django.contrib.auth import logout as log_out
from urllib.parse import urlencode, quote_plus
from social_django.models import UserSocialAuth
from decouple import config as dev_config
from django.conf import settings
import stripe
# below are imports related to oAuth
from django.contrib.auth import get_user_model
from django.contrib.auth import login as django_login
from django.contrib.auth import authenticate as django_auth
import requests
import jwt
from authlib.integrations.django_client import OAuth
from django.urls import reverse
from django.contrib import messages

# NOTE: we are only going to use json config files in the future
# this is how all configuration imports will work
# NOTE: this is temporary until we find a solution for checking whether we're in
# test mode
settings.DEBUG = True

if settings.DEBUG == True:
  pass
else:
  with open('/etc/ecommerce_config.json') as config_file:
    config = json.load(config_file)

if settings.DEBUG == True:
  stripe.api_key = dev_config("STRIPE_SECRET_KEY")
else:
  stripe.api_key = config["STRIPE_SECRET_KEY"]

oauth = OAuth()

oauth.register(
  "auth0",
  client_id=settings.SOCIAL_AUTH_AUTH0_KEY,
  client_secret=settings.SOCIAL_AUTH_AUTH0_SECRET,
  client_kwargs={
    "scope": "openid profile email",
  },
  server_metadata_url=f"https://{settings.SOCIAL_AUTH_AUTH0_DOMAIN}/.well-known/openid-configuration",
)

# Create your views here.
def base(request):
    return render(request, 'ecommerce/base.html')

@login_required
def profile(request):
  return render(request, 'ecommerce/profile.html', context={
    'userdata': {
      'name': 'hi'
    }
  })

def check_if_user_has_oauth_id(request):
  try:
    user = User.objects.get(username=request.POST['username'])
  except User.DoesNotExist:
    raise ValueError("User does not exist. Please create an account.")
  try:
    customer = user.customer
    if customer.oauth_user_id:
        print('inside customer has oauth user id')
        raise ValueError("User account is associated with an OAuth Id. Please use OAuth to login.")
  except Customer.DoesNotExist:
    # for our current flow, if a customer does not exist for this account
    # it does not necessarily mean that this should raise an error.
    # maybe the user does not want to authenticate with oAuth provider
    # should we just ask them here if they want to?
    # or show them a link to do so?
    # actually to make this more modular, let's make another function
    # to log in the user by django
    pass
  # if we hit the except block above, it just passes flow here, where we will use
  # default django authentication
  user_attempt_to_login = attempt_to_login_as_django_user(request)
  return user_attempt_to_login
  
def attempt_to_login_as_django_user(request):
  print('hello from attempt to login as django user')
  user = django_auth(request, username=request.POST['username'], password=request.POST['password'])
  if user is not None:
    print('inside user is not none')
    django_login(request, user)
    print('after django login')
    return redirect(reverse("ecommerce:profile"))
  else:
    raise ValueError("Invalid credentials. Please try again.")


def auth0_login(request):
  if request.method == 'POST' and 'username' in request.POST:
    try:
      print('before check if user has oauth id')
      user_has_oauth_id = check_if_user_has_oauth_id(request)
      if user_has_oauth_id:
        return user_has_oauth_id
    except ValueError as e:
      # if we hit the except block it's because one of our ValueErrors was raised
      # so we use django's messaging framework to notify the user
      messages.error(request, str(e))
      return redirect(request.build_absolute_uri(reverse("ecommerce:index")))
  # if there is no error raised, then we continue with the login process
  return oauth.auth0.authorize_redirect(
    request, request.build_absolute_uri(reverse("ecommerce:callback"))
  )

def callback(request):
  token = oauth.auth0.authorize_access_token(request)
  request.session["user"] = token

  # insecure, we need to use user_info = oauth.auth0.parse_id_token(request, token) to verify JWT's signature
  if "user" in request.session and "userinfo" in request.session.get("user"):
    user_info = request.session.get("user")["userinfo"]
  else:
    user_info = None

  try:
    django_user = build_user_and_customer_model_and_return_django_user(user_info)
  except ValueError as e:
    messages.error(request, str(e))
    return redirect(request.build_absolute_uri(reverse("ecommerce:auth0_login")))

  # associate the user to the current session
  django_login(request, django_user, backend='django.contrib.auth.backends.ModelBackend')

  return redirect(request.build_absolute_uri(reverse("ecommerce:profile")))

def extract_oauth_user_id(oauth_string):
  return str(oauth_string.split("|")[-1])

def check_if_user_has_oauth_profile_before_creating_new_one(extracted_user_info):
  username = extracted_user_info.nickname
  first_name = extracted_user_info.given_name
  last_name = extracted_user_info.family_name
  email_address = extracted_user_info.email
  oauth_user_id = extract_oauth_user_id(extracted_user_info.sub)
  User = get_user_model()
  try:
    # check if a user with the given username exists
    django_user = User.objects.get(username=username)
    try:
      # check if a customer with the user and oauth_user_id exists
      django_customer = Customer.objects.get(user=django_user, oauth_user_id=oauth_user_id)
    except Customer.DoesNotExist:
      print('inside customer does not exist')
      # if the user exists but the customer with the given oauth_user_id does not, raise an exception
      raise ValueError("This user is associated with another account. Please authenticate using Google Sign In.")
  except User.DoesNotExist:
    # if the user does not exist, then create one
    django_user = User.objects.create(username=username, first_name=first_name, last_name=last_name, email=email_address)
    django_user.set_unusable_password()
    django_user.save()
  return django_user

def build_user_and_customer_model_and_return_django_user(extracted_user_info):
  profile_picture = extracted_user_info.picture
  oauth_user_id = extract_oauth_user_id(extracted_user_info.sub)
  # Check if a user with the given OAuth profile already exists or needs to be created
  django_user = check_if_user_has_oauth_profile_before_creating_new_one(extracted_user_info)
  # at this point the user either exists with the right OAuth profile or a new User has been created
  django_customer, customer_created = Customer.objects.get_or_create(
    user=django_user,
    defaults={
      "oauth_user_id": oauth_user_id,
      "profile_picture": profile_picture
    }
  )
  
  # return the django user to be associated with the current session
  return django_user

def auth0_logout(request):
  request.session.clear()

  return redirect(
    f"https://{settings.SOCIAL_AUTH_AUTH0_DOMAIN}/v2/logout?"
    + urlencode(
      {
        "returnTo": request.build_absolute_uri(reverse("ecommerce:index")),
        "client_id": settings.SOCIAL_AUTH_AUTH0_KEY
      },
      quote_via=quote_plus
    ),
  )

def index(request):
  return render(
    request,
    "ecommerce/index.html",
    context={
      "session": request.session.get("user"),
      "pretty": json.dumps(request.session.get("user"), indent=4),
    }
  )

# we are adding filtration to our category results page
# I eventually want this to replace category results page
# REMOVE THE FOLLOWING LINE IN PRODUCTION!
# NOTE: SUPER IMPORTANT!!!
# We spent around a hour to debug this;
# category did not have a default value, therefore we were getting
# a positional argument missing, since in the url
# when we go to the empty url '' (which is just localhost:8000/ecomm/)
# has no parameter set such as 'localhost:8000/ecomm/generator/'
# that matches the url parameter catcher 'localhost:8000/ecomm/<str:category>/
def filter_results_page(request, category='generator'):

  if category == 'game_console':
    return game_console_filter_results_page(request, category)
  
  if category == 'home_decor':
    return home_decor_filter_results_page(request, category)

  if category == 'sports_nutrition':
    return sports_nutrition_filter_results_page(request, category)

  if category == 'kitchen_and_home_appliance':
    return kitchen_and_home_appliance_filter_results_page(request, category)
  
  # I don't think that it's a good idea to query the entire
  # dataset each time we want to return all the possible filters
  # we need to find some way to cache this?
  all_product_brands = Generator.objects.values('product_brand').distinct().order_by()
  all_product_fuel_types = Generator.objects.values('generator_fuel_type').distinct().order_by()
  all_product_classification_types = Generator.objects.values('generator_classification_type').distinct().order_by()

ecommerce_poc/ecommerce/templates/ecommerce/about_page.html
{% extends 'ecommerce/base.html' %}
{% load my_tags %}
{% load static %}
{% block content %}

  <!--Main layout-->
  <main class="my-5">
    <div class="container">
      <!--Section: Content-->
      <section class="text-center">
        <h4 class="mb-5"><strong>About Sauer Websites!</strong></h4>

        <div class="row">
          <div class="col-lg-12 col-md-12 mb-4">
            <div class="card">
              <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                <img src="{% static 'images/TravisGraduation-24.jpg' %}" class="img-fluid" />
                <a href="#!">
                  <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                </a>
              </div>
              <div class="card-body">
                <h5 class="card-title">A More Impactful Online Presence Is Just a Click Away</h5>
                <p class="card-text">Welcome to Sauer Websites! I specialize in customizing your business's online presence to create a seamless experience for your customers. I believe that a strong online presence is crucial for amplifying your return on investment, and I'm dedicated to helping you achieve that.

                  One of the key ways I achieve this is by building a solid DevOps foundation for your business's application. This means that new features can be implemented quickly and efficiently, without sacrificing security. I understand that security is a top priority for any business, and should never be treated as an afterthought.
                  
                  Sauer Websites is more than just a Web Application Development Company; I'm a professional who is passionate about helping businesses like yours succeed online. Contact me today to see how we can work together to take your business to the next level.
                </p>
                <a href="/ecomm/contact_us" class="btn btn-primary">Contact Me</a>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!--Section: Content-->
    </div>
  </main>
  <!--Main layout-->

  {% endblock content %}

ecommerce_poc/ecommerce/templates/ecommerce/cart_page.html
{% extends 'ecommerce/base.html' %}
{% load my_tags %}
{% block content %}

<!-- Container for demo purpose -->
<div class="container my-5 py-5">

    <!-- Section: Design block -->
    <section class="">
      <div class="row gx-lg-5">
        <div class="col-lg-8 mb-4 mb-md-0">
          <!-- Section: Product list -->
          <section class="mb-5">
            {% for item in cart_items %}
            <!-- Single item -->
            <div class="row border-bottom mb-4">
              <div class="col-md-2 mb-4 mb-md-0">
                <div
                     class="
                            bg-image
                            ripple
                            rounded-5
                            mb-4
                            overflow-hidden
                            d-block
                            "
                     data-ripple-color="light"
                     >
                  <img
                       src="{{ item.product_photos }}"
                       class="w-100"
                       alt=""
                       />
                  <a href="#!">
                    <div class="hover-overlay">
                      <div
                           class="mask"
                           style="background-color: hsla(0, 0%, 98.4%, 0.2)"
                           ></div>
                    </div>
                  </a>
                </div>
              </div>
  
              <div class="col-md-8 mb-4 mb-md-0">
                <p class="fw-bold">{{ item.product_name }}</p>
                <p class="mb-1">
                  <span class="text-muted me-2">category: </span><span>{{ item.product_category }}</span>
                </p>
                <p>
                  <span class="text-muted me-2">brand: </span
                    ><span>{{ item.product_brand }}</span>
                </p>
  
                <p class="mb-4">
                  <!-- add border-end to the list of classes to have a vertical border at the end of the a tag -->
                  <a href="/ecomm/remove_item_from_cart/{{ item.id }}/?current_view=cart" class="text-muted pe-3"
                     >
                     <small
                             ><i class="fas fa-trash me-2"></i>Remove</small
                    ></a>
                  <!-- <a href="" class="text-muted ps-3"
                     ><small
                             ><i class="fas fa-heart me-2"></i>Move to wish
                    list</small
                    ></a> -->
                </p>
              </div>
  
              <div class="col-md-2 mb-4 mb-md-0">
                <div class="form-outline mb-4">
                  <input
                         type="number"
                         id="typeNumber"
                         class="form-control"
                         value="{{ item.quantity }}"
                         min="1"
                         name="cart_page_quantity_to_remove"
                         readonly="true"
                         />
                  <label class="form-label" for="typeNumber"
                         >Quantity</label
                    >
                </div>
  
                <h5 class="mb-2">
                  <s class="text-muted me-2 small align-middle">${{ item.cart_item_total|divide:100 }}</s
                    ><span class="align-middle">${{ item.cart_item_total|divide:100 }}</span>
                </h5>
                <p class="text-danger"><small>Product On Sale: {{ item.product_on_sale }}</small></p>
              </div>
            </div>
            <!-- Single item -->
            {% endfor %}
          </section>
          <!-- Section: Product list -->
  
          <!-- Section: Details -->
          <section class="">
            <div class="mb-5">
              <p class="text-primary">
                <i class="fas fa-info-circle mr-1"></i> Do not delay the
                purchase, adding items to your cart does not mean booking
                them.
              </p>
            </div>
            
            <!-- I'm assuming we're going to need to create a delivery model and create a one-to-one field
            within it based on a product or user. if we think this through, a user should have exactly one
            delivery for exactly one product (or more depending on the quantity, but think product ID here as "one") -->
            <div class="mb-5">
              <h5 class="mb-4">Expected shipping delivery</h5>
  
              <p class="mb-0">TBD</p>
            </div>
  
            <div>
              <h5 class="mb-4">We accept</h5>
  
              <img
                   class="mr-2"
                   width="45px"
                   src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                   alt="Visa"
                   />
              <img
                   class="mr-2"
                   width="45px"
                   src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                   alt="American Express"
                   />
              <img
                   class="mr-2"
                   width="45px"
                   src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                   alt="Mastercard"
                   />
              <img
                   class="mr-2"
                   width="45px"
                   src="https://mdbootstrap.com/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.png"
                   alt="PayPal acceptance mark"
                   />
            </div>
          </section>
          <!-- Section: Details -->
        </div>
  
        <div class="col-lg-4 mb-4 mb-md-0">
          <!-- Section: Summary -->
          <section class="shadow-4 p-4 rounded-5 mb-4">
            <h5 class="mb-5">The total amount of</h5>
  
            <div class="d-flex justify-content-between mb-3">
              <span>Temporary amount </span>
              <span>${{ cart_total }}</span>
            </div>
            <div class="d-flex justify-content-between">
                <!--we need to add a shipping fee to our product model, or potentially even create a shipping model;
                we need to sit down and re-architect everything -->
              <span>Shipping </span>
              <span>Free</span>
            </div>
            <hr class="my-4" />
            <div class="d-flex justify-content-between fw-bold mb-5">
              <span>Cart Total (including VAT)</span>
              <span>${{ cart_total }}</span>
            </div>
  
            <a class="btn btn-primary btn-rounded w-100" href="/ecomm/user_checkout/">
              Go to checkout
            </a>
          </section>
          <!-- Section: Summary -->
  
          <!-- Section: Summary -->
          <section class="shadow-4 p-4 rounded-5">
            <h5 class="mb-4">Apply promo code</h5>
  
            <div class="d-flex align-items-center">
              <input
                     type="text"
                     class="form-control rounded me-1"
                     placeholder="Promo code"
                     />
              <button
                      type="button"
                      class="btn btn-link btn-rounded overflow-visible"
                      >
                Apply
              </button>
            </div>
          </section>
          <!-- Section: Summary -->
        </div>
      </div>
    </section>
    <!-- Section: Design block -->
  
  </div>
  <!-- Container for demo purpose -->

{% endblock content %}

ecommerce_poc/ecommerce/templates/ecommerce/contact_us_page_success.html
{% extends "ecommerce/base.html" %}
{% block content %}
<div class="container mb-5">
  <section>
    <p>
        Thank you {{ name }} for your email! <br><br>
        Your message has been sent to {{ email_from }}!
    </p>
    <div class="row">
      <div class="col-6">
        <a href="/ecomm/contact_us/">Send Another Message</a>
      </div>
      <div class="col-6">
        <a href="{% url 'ecommerce:profile' %}">Home Page</a>
      </div>
    </div>
  </section>
</div>
{% endblock %}

ecommerce_poc/ecommerce/templates/ecommerce/login.html
{% extends 'ecommerce/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<div class="container">
    <h2>Login</h2>
    <form action="{% url 'social:begin' 'auth0' %}" method="post">
        {% csrf_token %}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

ecommerce_poc/ecommerce/templates/ecommerce/profile.html
{% extends 'ecommerce/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<div class="container">
	<section style="background-color: #eee;">
		<div class="container py-5">
			<div class="row">
				<div class="col">
					<nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
						<ol class="breadcrumb mb-0">
							<li class="breadcrumb-item"><a href="#">Home</a></li>
							<li class="breadcrumb-item"><a href="#">User</a></li>
							<li class="breadcrumb-item active" aria-current="page">User Profile</li>
                            <li class="breadcrumb-item"><a href="{% url 'ecommerce:auth0_logout' %}">Logout</a></li>
						</ol>
					</nav>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-4">
					<div class="card mb-4">
						<div class="card-body text-center">
							<img src="{{ user.customer.profile_picture }}" alt="avatar" class="rounded-circle img-fluid" style="width: 150px;" />
							<h5 class="my-3">{{ user.username }}</h5>
							<p class="text-muted mb-1">Full Stack Developer</p>
							<p class="text-muted mb-4">Bay Area, San Francisco, CA</p>
							<div class="d-flex justify-content-center mb-2">
								<button type="button" class="btn btn-primary">Follow</button>
								<button type="button" class="btn btn-outline-primary ms-1">Message</button>
							</div>
						</div>
					</div>
					<div class="card mb-4 mb-lg-0">
						<div class="card-body p-0">
							<ul class="list-group list-group-flush rounded-3">
								<li class="list-group-item d-flex justify-content-between align-items-center p-3">
									<i class="fas fa-globe fa-lg text-warning"></i>
									<p class="mb-0">https://mdbootstrap.com</p>
								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center p-3">
									<i class="fab fa-github fa-lg" style="color: #333333;"></i>
									<p class="mb-0">mdbootstrap</p>
								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center p-3">
									<i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
									<p class="mb-0">@mdbootstrap</p>
								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center p-3">
									<i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
									<p class="mb-0">mdbootstrap</p>
								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center p-3">
									<i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
									<p class="mb-0">mdbootstrap</p>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-lg-8">
					<div class="card mb-4">
						<div class="card-body">
							<div class="row">
								<div class="col-sm-3">
									<p class="mb-0">Full Name</p>
								</div>
								<div class="col-sm-9">
									<p class="text-muted mb-0">
                                        {% if user.first_name %}
                                            {{ user.first_name }} {{ user.last_name }}
                                        {% else %}
                                            {{ user.username }}, please update your profile with your Full Name.
                                        {% endif %}
                                    </p>
								</div>
							</div>
							<hr />
							<div class="row">
								<div class="col-sm-3">
									<p class="mb-0">Email</p>
								</div>
								<div class="col-sm-9">
									<p class="text-muted mb-0">
                                        {% if user.email %}
                                            {{ user.email }}
                                        {% else %}
                                            {{ user.username }}, please update your profile with your Full Name.
                                        {% endif %}
                                    </p>
								</div>
							</div>
							<hr />
							<div class="row">
								<div class="col-sm-3">
									<p class="mb-0">Phone</p>
								</div>
								<div class="col-sm-9">
									<p class="text-muted mb-0">(097) 234-5678</p>
								</div>
							</div>
							<hr />
							<div class="row">
								<div class="col-sm-3">
									<p class="mb-0">Mobile</p>
								</div>
								<div class="col-sm-9">
									<p class="text-muted mb-0">(098) 765-4321</p>
								</div>
							</div>
							<hr />
							<div class="row">
								<div class="col-sm-3">
									<p class="mb-0">Address</p>
								</div>
								<div class="col-sm-9">
									<p class="text-muted mb-0">Bay Area, San Francisco, CA</p>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<div class="card mb-4 mb-md-0">
								<div class="card-body">
									<p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status</p>
									<p class="mb-1" style="font-size: .77rem;">Web Design</p>
									<div class="progress rounded" style="height: 5px;">
										<div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
									<div class="progress rounded" style="height: 5px;">
										<div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
									<div class="progress rounded" style="height: 5px;">
										<div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
									<div class="progress rounded" style="height: 5px;">
										<div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
									<div class="progress rounded mb-2" style="height: 5px;">
										<div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="card mb-4 mb-md-0">
								<div class="card-body">
									<p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status</p>
									<p class="mb-1" style="font-size: .77rem;">Web Design</p>
									<div class="progress rounded" style="height: 5px;">
										<div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
									<div class="progress rounded" style="height: 5px;">
										<div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
									<div class="progress rounded" style="height: 5px;">
										<div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
									<div class="progress rounded" style="height: 5px;">
										<div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
									<div class="progress rounded mb-2" style="height: 5px;">
										<div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
{% endblock content %}